[adobe-acrobat-hooman]
cliType = "morphe"
appPkgName = "com.adobe.reader"
apkSrc = "apkmirror"
apkType = "bundle"
archs = ["universal"]
appVersion = "latest"
[[adobe-acrobat-hooman.patches]]
name = "hooman"
repo = "hoomans-morphe-patches"
owner = "arandomhooman"
src = "github"
tag = "prerelease"

[speedtest-xtra]
cliType = "morphe"
appPkgName = "org.zwanoo.android.speedtest"
apkSrc = "apkmirror"
apkType = "apk"
archs = ["arm64-v8a", "x86_64"]
appVersion = "latest"
[[speedtest-xtra.patches]]
name = "xtra"
repo = "android-patches-xtra"
owner = "BholeyKaBhakt"
src = "github"

[tiktok-icysymmetra]
cliType = "morphe"
appPkgName = "com.zhiliaoapp.musically"
apkSrc = "apkmirror"
apkType = "apk"
archs = ["arm64-v8a"]
[[tiktok-icysymmetra.patches]]
name = "icysymmetra"
repo = "tiktok-patches-for-morphe"
owner = "icysymmetra"
src = "github"

[youtube-morphe]
cliType = "morphe"
buildModule = "true"
appPkgName = "com.google.android.youtube"
apkSrc = "apkmirror"
apkType = "apk"
archs = ["universal"]
appVersionCmd = "get_experimental_version com.google.android.youtube"
[[youtube-morphe.patches]]
name = "morphe"
repo = "morphe-patches"
owner = "MorpheApp"
src = "github"
cliOptions = "-e 'Custom branding' -OcustomName='YouTube Morphe' -e Theme -OdarkThemeBackgroundColor=#000000 -d 'Custom Header'"
rootCliOptions = "-d 'GmsCore Support'"

[youtube-music-morphe]
cliType = "morphe"
buildModule = "true"
appPkgName = "com.google.android.apps.youtube.music"
apkSrc = "apkmirror"
apkType = "apk"
archs = ["arm64-v8a", "x86_64"]
appVersionCmd = "get_experimental_version com.google.android.apps.youtube.music"
[[youtube-music-morphe.patches]]
name = "morphe"
repo = "morphe-patches"
owner = "MorpheApp"
src = "github"
cliOptions = "-e 'Custom branding' -OcustomName='YouTube Morphe' -e Theme -OdarkThemeBackgroundColor=#000000"
rootCliOptions = "-d 'GmsCore Support'"

[prime-video-hoo-dles]
cliType = "morphe"
appPkgName = "com.amazon.avod.thirdpartyclient"
apkSrc = "apkmirror"
apkType = "apk"
archs = ["arm64-v8a"]
appVersion = "latest"
[[prime-video-hoo-dles.patches]]
name = "hoo-dles"
repo = "morphe-patches"
owner = "hoo-dles"
src = "github"
cliOptions = "-e 'Rename Shared Permissions'"

[proton-vpn-paresh]
cliType = "morphe"
appPkgName = "ch.protonvpn.android"
apkSrc = "apkmirror"
apkType = "bundle"
archs = ["universal"]
appVersion = "latest"
[[proton-vpn-paresh.patches]]
name = "paresh"
repo = "paresh-patches"
owner = "Paresh-Maheshwari"
src = "gitlab"

[jiohotstar-paresh]
cliType = "morphe"
appPkgName = "in.startv.hotstar"
archs = ["universal"]
apkSrc = "apkmirror"
apkType = "apk"
[[jiohotstar-paresh.patches]]
name = "paresh"
repo = "paresh-patches"
owner = "Paresh-Maheshwari"
src = "gitlab"

[symfonium-binarymend]
cliType = "morphe"
appPkgName = "app.symfonik.music.player"
apkSrc = "apkmirror"
apkType = "bundle"
archs = ["universal"]
[[symfonium-binarymend.patches]]
name = "binarymend"
repo = "morphe-patches"
owner = "binarymend"
src = "github"

[x-shim-piko]
cliType = "morphe"
appPkgName = "com.twitter.android"
apkSrc = "apkmirror"
archs = ["universal"]
apkType = "bundle"
[[x-shim-piko.patches]]
name = "shim"
repo = "x-shim"
owner = "inotia00"
src = "gitlab"
[[x-shim-piko.patches]]
name = "piko"
repo = "piko"
owner = "crimera"
src = "github"

[instagram-piko]
cliType = "morphe"
appPkgName = "com.instagram.android"
apkSrc = "apkmirror"
apkType = "bundle"
archs = ["arm64-v8a", "x86_64"]
[[instagram-piko.patches]]
name = "piko"
repo = "piko"
owner = "crimera"
src = "github"

[discord-revenge]
cliType = "npatch"
appPkgName = "com.discord"
apkSrc = "apkmirror"
apkType = "bundle"
archs = ["universal"]
[[discord-revenge.patches]]
name = "revenge"
repo = "revenge-xposed"
owner = "revenge-mod"
src = "github"
filter = "app-release.apk"

[amazon-india-signed]
cliType = "apksigner"
appPkgName = "in.amazon.mShop.android.shopping"
apkSrc = "apkmirror"
apkType = "bundle"
archs = ["arm64-v8a"]

[amazon-alexa-signed]
cliType = "apksigner"
appPkgName = "com.amazon.dee.app"
apkSrc = "apkmirror"
apkType = "bundle"
archs = ["universal"]
