name: Releasing APK files
description: "a"
inputs:
  name:
    description: "Release name"
    required: true
  tag:
    description: "Release tag"
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo  -e "changelog wip"> ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: ncipollo/release-action@v1.21.0
      with:
        artifacts: |
          ./release/*.apk
        name: ${{ inputs.name }}
        tag: ${{ inputs.tag }}
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true
