name: Releasing APK files
description: "a"
inputs:
  name:
    description: "Release name"
    required: true
  tag:
    description: "Release tag"
    required: true
runs:
  using: "composite"
  steps:
    - name: Upload to archive
      uses: ncipollo/release-action@v1.21.0
      with:
        artifacts: |
          ./release/*.apk
          ./release/*.zip
        name: "Old APKs and zips"
        tag: "all"
        allowUpdates: true
    - name: Release
      uses: ncipollo/release-action@v1.21.0
      with:
        artifacts: |
          ./release/*.apk
          ./release/*.zip
        removeArtifacts: true
        name: ${{ inputs.name }}
        tag: ${{ inputs.tag }}
        allowUpdates: true

 