name: Always CI
permissions: write-all
on:
  schedule:
    - cron: "0 0/4 * * *"
  workflow_dispatch:

jobs:
  Patch-Revenge-Discord:
    name: Patch Revenge(Discord)
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revenge Discord"
    secrets: inherit
  Patch-Dolphin-SDK-29:
    name: Patch Dolphin SDK 29
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Dolphin SDK 29"
    secrets: inherit
  Amazon-India:
    name: Patch Amazon India
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Amazon India"
    secrets: inherit
  Amazon-Alexa:
    name: Patch Amazon Alexa
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Amazon Alexa"
    secrets: inherit
  Patch-hoo-dles-prime-video:
    name: Patch hoo-dles Prime Video
    uses: ./.github/workflows/manual-patch.yml
    secrets: inherit
    with:
      org: "hoo-dles Prime Video"
