name: CI
permissions: write-all
on:
  schedule:
    - cron: "0 0/4 * * *"
  workflow_dispatch:
    inputs:
      retry_count:
        description: 'Do not change value below'
        required: false
        default: '1'
jobs:
  check:
    name: Check new patch
    runs-on: ubuntu-latest
    env:
      repository: ${{ github.repository }}
      TDL_BACKUP: ${{ secrets.TDL_BACKUP }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Check new patch Morphe YouTube
        id: check-morphe
        run: bash scripts/checker.sh youtube-morphe
      - name: Check new patch Piko(Instagram)
        id: check-piko-instagram
        run: bash scripts/checker.sh instagram-piko
      - name: Check new patch binarymend 
        id: check-binarymend
        run: bash src/etc/checker.sh symfonium-binarymend
      - name: Check new app FCL
        id: check-fcl
        run: bash src/etc/checker.sh fcl-cod
      - name: Check new app Geode
        id: check-geode
        run: bash src/etc/checker.sh geode-pubgkr
      - name: Check new app LeviLauncher Unlocked
        id: check-levilauncher
        run: bash src/etc/checker.sh levilauncher-unlocked-bgmi
      - name: Check new app Winlator
        id: check-winlator
        run: bash src/etc/checker.sh winlator-pubgvn
      - name: Check new patch icysymmetra
        id: check-icysymmetra
        run: bash src/etc/checker.sh tiktok-icysymmetra
    outputs:
      check_morphe: ${{ steps.check-morphe.outputs.new_patch }}
      check_piko_instagram: ${{ steps.check-piko-instagram.outputs.new_patch }}
      check_binarymend: ${{ steps.check-binarymend.outputs.new_patch }}
      check_fcl: ${{ steps.check-fcl.outputs.new_patch }}
      check_geode: ${{ steps.check-geode.outputs.new_patch }}
      check_icysymmetra: ${{ steps.check-icysymmetra.outputs.new_patch }}
      check_winlator: ${{ steps.check-winlator.outputs.new_patch }}
      check_levilauncher: ${{ steps.check-levilauncher.outputs.new_patch }}
  Patch-Morphe:
    name: Patch Morphe
    needs: check
    if: ${{ needs.check.outputs.check_morphe == 1 }}
    uses: ./.github/workflows/new_manual-patch.yml
    secrets: inherit
    with:
      patch: "Morphe"
  Patch-Piko-X:
    name: Patch Piko(X)
    needs: check
    uses: ./.github/workflows/new_manual-patch.yml
    secrets: inherit
    with:
      patch: "Piko (with shim)"
  Patch-Piko-Instagram:
    name: Patch Piko(Instagram)
    needs: check
    if: ${{ needs.check.outputs.check_piko_instagram == 1 }}
    uses: ./.github/workflows/new_manual-patch.yml
    secrets: inherit
    with:
      patch: "Piko"
  Patch-paresh:
    name: Patch Paresh
    needs: check
    uses: ./.github/workflows/new_manual-patch.yml
    secrets: inherit
    with:
      patch: "Paresh"
  Patch-binarymend:
    name: Patch binarymend
    needs: check
    if: ${{ needs.check.outputs.check_binarymend == 1 }}
    uses: ./.github/workflows/new_manual-patch.yml
    secrets: inherit
    with:
      patch: "binarymend"
  Patch-FCL:
    name: Patch FCL
    needs: check
    if: ${{ needs.check.outputs.check_fcl == 1 }}
    uses: ./.github/workflows/fcl.yml
    secrets: inherit
  Patch-Geode:
    name: Patch Geode
    needs: check
    if: ${{ needs.check.outputs.check_geode == 1 }}
    uses: ./.github/workflows/geode.yml
    secrets: inherit
  Patch-Custom:
    name: Patch Custom
    needs: check
    uses: ./.github/workflows/new_manual-patch.yml
    with:
      patch: "Custom"
    secrets: inherit
  Patch-Revenge:
    name: Patch Revenge
    uses: ./.github/workflows/new_manual-patch.yml
    with:
      patch: "Revenge"
    secrets: inherit
  sign:
    name: Sign
    needs: check
    uses: ./.github/workflows/new_manual-patch.yml
    with:
      patch: "Sign"
    secrets: inherit
  Patch-Hooman:
    name: Patch Hooman
    needs: check
    uses: ./.github/workflows/new_manual-patch.yml
    with:
      patch: "Hooman"
    secrets: inherit
  Patch-Icysymmetra:
    name: Patch Icysymmetra
    needs: check
    if: ${{ needs.check.outputs.check_icysymmetra == 1 }} 
    uses: ./.github/workflows/new_manual-patch.yml
    with:
      patch: "Icysymmetra"
  Patch-hoo-dles:
    name: Patch hoo-dles
    uses: ./.github/workflows/new_manual-patch.yml
    secrets: inherit
    with:
      patch: "hoo-dles"
  Patch-LeviLauncher-Unlocked:
    name: Patch LeviLauncher Unlocked
    needs: check
    if: ${{ needs.check.outputs.check_levilauncher == 1 }}
    uses: ./.github/workflows/levilauncher.yml
    secrets: inherit
