name: Manual Patch
permissions: write-all

env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which apps do you want to patch?'
        required: true
        default: 'All'
        type: choice
        options:
          - 'All'
          - 'Morphe YouTube'
          - 'Morphe YouTube Music'
          - 'piko X'
          - 'piko Instagram'
          - 'Paresh Proton VPN'
          - 'Paresh JioHotstar'
          - 'hoo-dles Prime Video'
          - 'binarymend Symfonium'
          - 'Revenge Discord'
          - 'Dolphin SDK 29'
          - 'Eden PUBG'
          - 'FCL CoD'
          - 'Geode PUBGKR'
          - 'Winlator PUBGVN'
          - 'Amazon India'
          - 'Amazon Alexa'
          - 'Speedtest Xtra'
          - 'Adobe Acrobat Hooman'
          - 'TikTok Icysymmetra'
  workflow_call:
    inputs:
      org:
        required: true
        type: string
    secrets:
      TDL_BACKUP:
        required: false

jobs:
  patch:
    name: Patch ${{ matrix.label }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - org: Morphe YouTube
            label: Morphe (YouTube)
            build_target: morphe-youtube
            release_name: YouTube - Morphe
            release_tag: youtube-morphe
          - org: Morphe YouTube Music
            label: Morphe (YouTube Music)
            build_target: morphe-youtube-music
            release_name: YouTube Music - Morphe
            release_tag: youtube-music-morphe
          - org: piko X
            label: Piko (X)
            build_target: piko-x
            release_name: X (Twitter) - Piko
            release_tag: x-piko
          - org: piko Instagram
            label: Piko (Instagram)
            build_target: piko-instagram
            release_name: Instagram - Piko
            release_tag: instagram-piko
          - org: Paresh Proton VPN
            label: Paresh (Proton VPN)
            build_target: paresh-protonvpn
            release_name: Proton VPN - Paresh
            release_tag: proton-vpn-paresh
          - org: Paresh JioHotstar
            label: Paresh (JioHotstar)
            build_target: paresh-jiohotstar
            release_name: JioHotstar - Paresh
            release_tag: jiohotstar-paresh
          - org: hoo-dles Prime Video
            label: hoo-dles (Prime Video)
            build_target: hoo-dles-prime-video
            release_name: Prime Video - hoo-dles
            release_tag: prime-video-hoo-dles
          - org: binarymend Symfonium
            label: binarymend (Symfonium)
            build_target: binarymend-symfonium
            release_name: Symfonium - binarymend
            release_tag: symfonium-binarymend
          - org: Revenge Discord
            label: Revenge Discord
            build_target: revenge-discord
            release_name: Discord - Revenge
            release_tag: discord-revenge
          - org: Amazon India
            label: Amazon India
            build_target: amazon-india
            release_name: Amazon India
            release_tag: amazon-india
          - org: Amazon Alexa
            label: Amazon Alexa
            build_target: amazon-alexa
            release_name: Amazon Alexa
            release_tag: amazon-alexa
          - org: Dolphin SDK 29
            label: Dolphin SDK 29
            build_target: dolphin-sdk-29
            release_name: Dolphin SDK 29
            release_tag: dolphin-sdk-29
          - org: Eden PUBG
            label: Eden PUBG
            build_target: eden-pubg
            release_name: Eden PUBG
            release_tag: eden-pubg
          - org: FCL CoD
            label: FCL CoD
            build_target: fcl-cod
            release_name: FCL CoD
            release_tag: fcl-cod
          - org: Geode PUBGKR
            label: Geode PUBGKR
            build_target: geode-pubgkr
            release_name: Geode PUBGKR
            release_tag: geode-pubgkr
          - org: Winlator PUBGVN
            label: Winlator PUBGVN
            build_target: winlator-pubgvn
            release_name: Winlator PUBGVN
            release_tag: winlator-pubgvn
          - org: Adobe Acrobat Hooman
            label: Adobe Acrobat Hooman
            build_target: adobe-acrobat-hooman
            release_name: Adobe Acrobat - Hooman
            release_tag: adobe-acrobat-hooman
          - org: Speedtest Xtra
            label: Speedtest Xtra
            build_target: speedtest-xtra
            release_name: Speedtest Xtra
            release_tag: speedtest-xtra
          - org: TikTok Icysymmetra
            label: TikTok Icysymmetra
            build_target: tiktok-icysymmetra
            release_name: TikTok - Icysymmetra
            release_tag: tiktok-icysymmetra
            
    steps:
      - name: Check Match
        id: match-check
        run: |
          if [ "${{ inputs.org }}" = "All" ] || [ "${{ inputs.org }}" = "${{ matrix.org }}" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Decode Keystore
        shell: bash
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ks.keystore
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh
        shell: bash
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        if: steps.check-gh.outputs.internet_error == '0'
        run: |
          bash src/build/build.sh ${{ matrix.build_target }}
      - name: Releasing APK files
        id: release
        if: steps.check-gh.outputs.internet_error == '0'
        uses: ./.github/actions/release
        with:
          name: ${{ matrix.release_name }}
          tag: ${{ matrix.release_tag }}