name: Build and Patch
permissions: write-all

env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      patch:
        description: 'Which patch do you want to apply?'
        required: true
        default: 'All'
        type: choice
        options:
          - 'All'
          - 'Morphe'
          - 'Piko(with shim)'
          - 'Piko'
          - 'Paresh'
          - 'hoo-dles'
          - 'binarymend'
          - 'Revenge'
          - 'Custom (Dolphin)'
          - 'Custom (Eden)'
          - 'Custom (Winlator)'
          - 'Sign'
          - 'Hooman'
          - 'Icysymmetra'
          - 'Xtra'
  workflow_call:
    inputs:
      patch:
        required: true
        type: string

jobs:
  patch:
    name: Patch ${{ matrix.app }} with ${{ matrix.patch }} patch
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - app: YouTube
            patch: Morphe
            appname: youtube
            patchname: morphe
          - app: YouTube Music
            patch: Morphe
            appname: youtube-music
            patchname: morphe
          - app: X
            patch: Piko (with shim)
            appname: x
            patchname: shim-piko
          - app: Instagram
            patch: Piko
            appname: instagram
            patchname: piko
          - app: Proton VPN
            patch: Paresh
            appname: proton-vpn
            patchname: paresh
          - app: JioHotstar
            patch: Paresh
            appname: jiohotstar
            patchname: paresh
          - app: Prime Video
            patch: hoo-dles
            appname: prime-video
            patchname: hoo-dles
          - app: Symfonium
            patch: binarymend
            appname: symfonium
            patchname: binarymend
          - app: Discord
            patch: Revenge
            appname: discord
            patchname: revenge
          - app: Dolphin
            patch: Custom (Dolphin)
            suffix: SDK29
            appname: dolphin
            patchname: sdk29
          - app: Eden Nightly
            patch: Custom (Eden)
            suffix: PUBG
            appname: eden
            patchname: pubg
          - app: Winlator 
            suffix: PUBGVN
            patch: Custom (Winlator)
            appname: winlator
            patchname: pubgvn
          - app: Amazon India
            patch: Sign
            appname: amazon-india
            patchname: signed
          - app: Amazon Alexa
            patch: Sign
            appname: amazon-alexa
            patchname: signed
          - app: Speedtest
            patch: Xtra
            appname: speedtest
            patchname: xtra
          - app: Adobe Acrobat
            patch: Hooman
            appname: adobe-acrobat
            patchname: hooman
          - app: TikTok
            patch: Icysymmetra
            appname: tiktok
            patchname: icysymmetra
          
            
    steps:
      - name: Check Match
        id: match-check
        run: |
          if [ "${{ inputs.patch }}" = "All" ] || [ "${{ inputs.patch }}" = "${{ matrix.patch }}" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ks.keystore
      - name: Download and Setup FlareSolverr
        run: |
          docker run -d --name flaresolverr -p 8191:8191 ghcr.io/flaresolverr/flaresolverr:latest
          echo "[*] Waiting for FlareSolverr to start..."
          for i in $(seq 1 30); do
            if curl -s http://localhost:8191/ > /dev/null 2>&1; then
              echo "[+] FlareSolverr is ready."
              break
            fi
            sleep 2
          done
      - name: Patch APK
        id: patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          appname: ${{ matrix.appname }}
          patchname: ${{ matrix.patchname }}
          github_repo: $GITHUB_REPOSITORY
        run: |
          if [ "${{ matrix.patch }}" == "Custom" ]; then
            echo -e "relname=\"${{ matrix.app }} - ${{ matrix.suffix }}\"" >> $GITHUB_OUTPUT
            bash src/build/custom_patches.sh $appname-$patchname && echo "build_success=true" >> $GITHUB_OUTPUT || echo "build_success=false" >> $GITHUB_OUTPUT
          else
            echo -e "relname=\"${{ matrix.app }} - ${{ matrix.patch }}\"" >> $GITHUB_OUTPUT
            bash src/build/build.sh && echo "build_success=true" >> $GITHUB_OUTPUT || echo "build_success=false" >> $GITHUB_OUTPUT
          fi
      - name: Tailored Release
        uses: ncipollo/release-action@v1
        if: steps.patch.outputs.build_success == 'true' && steps.match-check.outputs.should_run == 'true'
        with:
          artifacts: |
            ./release/*
          name: ${{ steps.patch.outputs.relname }}
          tag: ${{ matrix.appname }}-${{ matrix.patchname }}
          allowUpdates: true
          removeArtifacts: true
          bodyFile: CHANGELOG.md
      - name: Upload to Archive Release
        uses: ncipollo/release-action@v1
        if: steps.patch.outputs.build_success == 'true' && steps.match-check.outputs.should_run == 'true'
        with:
          artifacts: |
            ./release/*
          name: "Old APKs"
          tag: "archive"
          allowUpdates: true
          makeLatest: true
          body: "This release contains some of the old APKs that have been patched and released in the past. You can download any of the old APKs from this release."

        