name: Update submodules
permissions: write-all
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/4 * * *"
jobs:
    update-submodules:
        name: Update submodules
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                fetch-depth: 0
                submodules: recursive
            - name: Update submodules
              run: |
                git submodule update --remote --recursive
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git commit -am "Update submodules"
                git push